### ISSUE TITLE
Portfolio design 

### ISSUE THREAD

**Issue by medijdir** [mulugithub/Microverse-Portfolio#8]
Hi @mulugithub ,
![Bh187WaynesWorldGIF](https://github.com/mulugithub/Microverse-Portfolio/assets/123473630/800edf4b-f692-42f1-9b7f-8c218bf0d5b2)
Congratulations, well done!!! 👍 
We kindly suggest the following issues:
- It is recommended to use white border color on "the get in touch" button for accessibility reasons.
- It also is recommended that the image should not cover the text when hovering it. 
- kindly stick to the Figma design for the card images because the margin it should be the same ♻️

**Comment by mulugithub** [comment]
## The issues were fixed.
 _Thank you all for your constructive feedback since it helps me improve the portfolio project._ 👍 


[Check Live demo ](https://mulugithub.github.io/Microverse-Portfolio/)

**_Remarks:_** It is recommended to use a white border color on "the get in touch" button for accessibility reasons. This issue is not part of the requirement. I have done this while working on the project, and the code reviewer suggested that I kindly remove the white border color since there is no requirement.
